name: NodeJS application

on:
  push:
    branches: [ beta ]
    
jobs:  

  BuildAndTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: |
        cd urrevs
        npm install
    - name: Testing Server
      run: |
        cd urrevs
        npm install mocha chai chai-http supertest --save-dev
        export DB_URI=mongodb+srv://urrevs:urrevsrocks@urrevs-local.mxhif.mongodb.net/urrevs?retryWrites=true&w=majority
        npm start &
        PID=$!
        sleep 5
        kill $PID


  DeployToHerokuMobile:
    needs: [BuildAndTest]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: "58fa067b-c30c-4ed9-a382-06d609d93b02"
        heroku_email: ${{ secrets.MAIL }}
        heroku_app_name: urrevs-api-dev-mobile
        appdir: "urrevs" # (Optional) used when the api is in a sub-directory. you can add slashes (/) in case of sub-sub directories
        #buildpack: "https://github.com/ddollar/heroku-buildpack-multi.git"

  DeployToHerokuWeb:
    needs: [DeployToHerokuMobile]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: "58fa067b-c30c-4ed9-a382-06d609d93b02"
        heroku_email: ${{ secrets.MAIL }}
        heroku_app_name: urrevs-api-dev-web
        appdir: "urrevs" # (Optional) used when the api is in a sub-directory. you can add slashes (/) in case of sub-sub directories
        #buildpack: "https://github.com/ddollar/heroku-buildpack-multi.git"


  mergeToMain:
    needs: [DeployToHerokuWeb]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge staging -> main
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: main
          github_token: ${{ github.token }}