name: NodeJS application

on:
  pull_request:
    branches: [ beta ]

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: |
        cd urrevs
        npm install
    - name: Testing Server
      run: |
        cd urrevs
      # npm install mocha chai chai-http supertest --save-dev
        npm start &
        PID=$!
        sleep = 5
        kill $PID